### ISSUE TITLE
Duplication of the People list in every Group

### ISSUE THREAD

**Issue by ncarding** [ncarding/NavViewTemplate#1]
The People lists should be independent of the Group lists, but at the moment they are not.

If you add a new Group then add one or more People to that group and then add a second Group, the People from the first Group are automatically added to the second and any additional Groups. 

I can't tell where the bug is but it only effects Groups created with each launch of the app. E.g. If you create three Groups they will all contain the same People. If you then quit the app and relaunch it those people will still be in each Group but if you create more Groups they will not contain the original list of People. These new Groups will however all share any new People added to any of the Groups created in this session.

**Comment by cclauss** [comment]
Does https://github.com/ncarding/NavViewTemplate/pull/2 solve this?

**Comment by ncarding** [comment]
Yes it does! Thank you so much I don't think I would ever have weeks that out. Any chance you could explain what was happening before you made that change and why this change fixed. That way hopefully I won't make the same mistake again.

**Comment by cclauss** [comment]
Please close this issue.

https://www.google.com/search?q=python+mutable+default

**Comment by ncarding** [comment]
Thanks
